---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Simple DynamoDB Table with id and range column
Parameters:
  TableName:
    Description: Name of DynamoDB table
    Type: String
  TableIdColumnName:
    Description: Name of DynamoDB table id column. Id column created is of type String
    Type: String
  TableRangeColumnName:
    Description: Name of DynamoDB table range column. range column created is of type String
    Type: String
Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableName
      AttributeDefinitions:
      - AttributeName:
          Ref: TableIdColumnName
        AttributeType: S
      - AttributeName:
          Ref: TableRangeColumnName
        AttributeType: S
      KeySchema:
      - AttributeName:
          Ref: TableIdColumnName
        KeyType: HASH
      - AttributeName:
          Ref: TableRangeColumnName
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
